//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/customessages/SpeedLimitation.msg.
//

#ifndef __VEINS_SPEEDLIMITATION_M_H
#define __VEINS_SPEEDLIMITATION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class SpeedLimitation;
} // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/customessages/SpeedLimitation.msg:22</tt> by nedtool.
 * <pre>
 * message SpeedLimitation extends BaseFrame1609_4
 * {
 *     int speedLimit;
 *     int speedbumpId;
 * 
 * }
 * </pre>
 */
class VEINS_API SpeedLimitation : public ::veins::BaseFrame1609_4
{
  protected:
    int speedLimit = 0;
    int speedbumpId = 0;

  private:
    void copy(const SpeedLimitation& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SpeedLimitation&);

  public:
    SpeedLimitation(const char *name=nullptr, short kind=0);
    SpeedLimitation(const SpeedLimitation& other);
    virtual ~SpeedLimitation();
    SpeedLimitation& operator=(const SpeedLimitation& other);
    virtual SpeedLimitation *dup() const override {return new SpeedLimitation(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSpeedLimit() const;
    virtual void setSpeedLimit(int speedLimit);
    virtual int getSpeedbumpId() const;
    virtual void setSpeedbumpId(int speedbumpId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SpeedLimitation& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SpeedLimitation& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_SPEEDLIMITATION_M_H

